
#ifndef TAILOREDSOLVER_CASADI_H
#define TAILOREDSOLVER_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int TailoredSolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void TailoredSolver_objective_1_incref(void);

const casadi_int* TailoredSolver_objective_1_sparsity_out(casadi_int i);

int TailoredSolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void TailoredSolver_dynamics_1_incref(void);

const casadi_int* TailoredSolver_dynamics_1_sparsity_out(casadi_int i);

int TailoredSolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void TailoredSolver_inequalities_1_incref(void);

const casadi_int* TailoredSolver_inequalities_1_sparsity_out(casadi_int i);

int TailoredSolver_objective_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void TailoredSolver_objective_30_incref(void);

const casadi_int* TailoredSolver_objective_30_sparsity_out(casadi_int i);

int TailoredSolver_inequalities_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void TailoredSolver_inequalities_30_incref(void);

const casadi_int* TailoredSolver_inequalities_30_sparsity_out(casadi_int i);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
