% TailoredSolver - a fast solver generated by FORCESPRO v6.0.0
%
%   OUTPUT = TailoredSolver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.lb - column vector of length 360
%       PARAMS.ub - column vector of length 360
%       PARAMS.hu - column vector of length 80
%       PARAMS.xinit - column vector of length 7
%       PARAMS.x0 - column vector of length 360
%       PARAMS.all_parameters - column vector of length 1080
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.U - column vector of size 160
%       OUTPUT.X - column vector of size 200
%
%   [OUTPUT, EXITFLAG] = TailoredSolver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -6 - NaN or INF occured during evaluation of functions and derivatives. Please check your initial guess.
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%     -98 - Thread error
%     -99 - Locking mechanism error
%    -100 - License error
%    -101 - Insufficient number of internal memory instances
%    -102 - Number of threads larger than specified
%
%   [OUTPUT, EXITFLAG, INFO] = TailoredSolver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it         - number of iterations that lead to this result
%       INFO.res_eq     - max. equality constraint residual
%       INFO.res_ineq   - max. inequality constraint residual
%       INFO.rsnorm     - norm of stationarity condition
%       INFO.rcompnorm  - max of all complementarity violations
%       INFO.pobj       - primal objective
%       INFO.mu         - duality measure
%       INFO.solvetime  - time needed for solve (wall clock time)
%       INFO.fevalstime - time needed for function evaluations (wall clock time)
%       INFO.solver_id  - solver ID of FORCESPRO solver
%
% See also COPYING
